# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('curso', models.CharField(max_length=200)),
                ('ra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlunoNotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('curso', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=200)),
                ('nota', models.CharField(max_length=20)),
                ('idcelular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('turma', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=200)),
                ('campus', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=200)),
                ('horarioteoria', models.CharField(max_length=20)),
                ('horariopratica', models.CharField(max_length=20)),
                ('professor', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.AddField(
            model_name='alunolista',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='quickstart.Turma'),
        ),
    ]
